/*

This file was generated by the "C - Kessels engine grammar.h" template.

*/


#define GrammarCharset0CharCount 7
wchar_t GrammarCharset0[7+1] = {
  9,
  10,
  11,
  12,
  13,
  32,
  160,
  0};
#define GrammarCharset1CharCount 1
wchar_t GrammarCharset1[1+1] = {
  42,
  0};
#define GrammarCharset2CharCount 1
wchar_t GrammarCharset2[1+1] = {
  35,
  0};
#define GrammarCharset3CharCount 1
wchar_t GrammarCharset3[1+1] = {
  45,
  0};
#define GrammarCharset4CharCount 1
wchar_t GrammarCharset4[1+1] = {
  39,
  0};
#define GrammarCharset5CharCount 1
wchar_t GrammarCharset5[1+1] = {
  40,
  0};
#define GrammarCharset6CharCount 1
wchar_t GrammarCharset6[1+1] = {
  41,
  0};
#define GrammarCharset7CharCount 1
wchar_t GrammarCharset7[1+1] = {
  44,
  0};
#define GrammarCharset8CharCount 25
wchar_t GrammarCharset8[25+1] = {
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  0};
#define GrammarCharset9CharCount 21
wchar_t GrammarCharset9[21+1] = {
  98,
  99,
  100,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset10CharCount 1
wchar_t GrammarCharset10[1+1] = {
  47,
  0};
#define GrammarCharset11CharCount 1
wchar_t GrammarCharset11[1+1] = {
  82,
  0};
#define GrammarCharset12CharCount 1
wchar_t GrammarCharset12[1+1] = {
  97,
  0};
#define GrammarCharset13CharCount 1
wchar_t GrammarCharset13[1+1] = {
  101,
  0};
#define GrammarCharset14CharCount 1
wchar_t GrammarCharset14[1+1] = {
  109,
  0};
#define GrammarCharset15CharCount 1
wchar_t GrammarCharset15[1+1] = {
  110,
  0};
#define GrammarCharset16CharCount 1
wchar_t GrammarCharset16[1+1] = {
  111,
  0};
#define GrammarCharset17CharCount 62
wchar_t GrammarCharset17[62+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset18CharCount 61
wchar_t GrammarCharset18[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset19CharCount 1
wchar_t GrammarCharset19[1+1] = {
  69,
  0};
#define GrammarCharset20CharCount 61
wchar_t GrammarCharset20[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset21CharCount 1
wchar_t GrammarCharset21[1+1] = {
  77,
  0};
#define GrammarCharset22CharCount 60
wchar_t GrammarCharset22[60+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  109,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset23CharCount 1
wchar_t GrammarCharset23[1+1] = {
  108,
  0};
#define GrammarCharset24CharCount 61
wchar_t GrammarCharset24[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset25CharCount 61
wchar_t GrammarCharset25[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  97,
  98,
  99,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset26CharCount 1
wchar_t GrammarCharset26[1+1] = {
  100,
  0};
#define GrammarCharset27CharCount 61
wchar_t GrammarCharset27[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  121,
  122,
  0};
#define GrammarCharset28CharCount 1
wchar_t GrammarCharset28[1+1] = {
  120,
  0};
#define GrammarCharset29CharCount 61
wchar_t GrammarCharset29[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset30CharCount 1
wchar_t GrammarCharset30[1+1] = {
  105,
  0};
#define GrammarCharset31CharCount 61
wchar_t GrammarCharset31[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset32CharCount 1
wchar_t GrammarCharset32[1+1] = {
  115,
  0};
#define GrammarCharset33CharCount 61
wchar_t GrammarCharset33[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset34CharCount 1
wchar_t GrammarCharset34[1+1] = {
  116,
  0};
#define GrammarCharset35CharCount 61
wchar_t GrammarCharset35[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset36CharCount 61
wchar_t GrammarCharset36[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset37CharCount 1
wchar_t GrammarCharset37[1+1] = {
  117,
  0};
#define GrammarCharset38CharCount 61
wchar_t GrammarCharset38[61+1] = {
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  0};
#define GrammarCharset39CharCount 1
wchar_t GrammarCharset39[1+1] = {
  114,
  0};


/*
struct DfaEdgeStruct {
  int TargetState;
  int CharCount;
  wchar_t *CharacterSet;
  };
*/
struct DfaEdgeStruct GrammarDfaEdgeArray0[17+1] = {
  {1,GrammarCharset0CharCount,GrammarCharset0},
  {2,GrammarCharset1CharCount,GrammarCharset1},
  {4,GrammarCharset2CharCount,GrammarCharset2},
  {5,GrammarCharset3CharCount,GrammarCharset3},
  {7,GrammarCharset4CharCount,GrammarCharset4},
  {8,GrammarCharset5CharCount,GrammarCharset5},
  {9,GrammarCharset6CharCount,GrammarCharset6},
  {10,GrammarCharset7CharCount,GrammarCharset7},
  {11,GrammarCharset8CharCount,GrammarCharset8},
  {13,GrammarCharset9CharCount,GrammarCharset9},
  {15,GrammarCharset10CharCount,GrammarCharset10},
  {18,GrammarCharset11CharCount,GrammarCharset11},
  {21,GrammarCharset12CharCount,GrammarCharset12},
  {26,GrammarCharset13CharCount,GrammarCharset13},
  {32,GrammarCharset14CharCount,GrammarCharset14},
  {37,GrammarCharset15CharCount,GrammarCharset15},
  {40,GrammarCharset16CharCount,GrammarCharset16},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray1[1+1] = {
  {1,GrammarCharset0CharCount,GrammarCharset0},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray2[1+1] = {
  {3,GrammarCharset10CharCount,GrammarCharset10},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray3[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray4[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray5[1+1] = {
  {6,GrammarCharset3CharCount,GrammarCharset3},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray6[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray7[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray8[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray9[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray10[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray11[1+1] = {
  {12,GrammarCharset17CharCount,GrammarCharset17},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray12[1+1] = {
  {12,GrammarCharset17CharCount,GrammarCharset17},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray13[1+1] = {
  {14,GrammarCharset17CharCount,GrammarCharset17},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray14[1+1] = {
  {14,GrammarCharset17CharCount,GrammarCharset17},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray15[2+1] = {
  {16,GrammarCharset10CharCount,GrammarCharset10},
  {17,GrammarCharset1CharCount,GrammarCharset1},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray16[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray17[0+1] = {
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray18[2+1] = {
  {12,GrammarCharset18CharCount,GrammarCharset18},
  {19,GrammarCharset19CharCount,GrammarCharset19},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray19[2+1] = {
  {12,GrammarCharset20CharCount,GrammarCharset20},
  {20,GrammarCharset21CharCount,GrammarCharset21},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray20[1+1] = {
  {12,GrammarCharset17CharCount,GrammarCharset17},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray21[3+1] = {
  {14,GrammarCharset22CharCount,GrammarCharset22},
  {22,GrammarCharset23CharCount,GrammarCharset23},
  {24,GrammarCharset15CharCount,GrammarCharset15},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray22[2+1] = {
  {14,GrammarCharset24CharCount,GrammarCharset24},
  {23,GrammarCharset23CharCount,GrammarCharset23},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray23[1+1] = {
  {14,GrammarCharset17CharCount,GrammarCharset17},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray24[2+1] = {
  {14,GrammarCharset25CharCount,GrammarCharset25},
  {25,GrammarCharset26CharCount,GrammarCharset26},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray25[1+1] = {
  {14,GrammarCharset17CharCount,GrammarCharset17},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray26[2+1] = {
  {14,GrammarCharset27CharCount,GrammarCharset27},
  {27,GrammarCharset28CharCount,GrammarCharset28},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray27[2+1] = {
  {14,GrammarCharset29CharCount,GrammarCharset29},
  {28,GrammarCharset30CharCount,GrammarCharset30},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray28[2+1] = {
  {14,GrammarCharset31CharCount,GrammarCharset31},
  {29,GrammarCharset32CharCount,GrammarCharset32},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray29[2+1] = {
  {14,GrammarCharset33CharCount,GrammarCharset33},
  {30,GrammarCharset34CharCount,GrammarCharset34},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray30[2+1] = {
  {14,GrammarCharset31CharCount,GrammarCharset31},
  {31,GrammarCharset32CharCount,GrammarCharset32},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray31[1+1] = {
  {14,GrammarCharset17CharCount,GrammarCharset17},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray32[2+1] = {
  {14,GrammarCharset35CharCount,GrammarCharset35},
  {33,GrammarCharset16CharCount,GrammarCharset16},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray33[2+1] = {
  {14,GrammarCharset25CharCount,GrammarCharset25},
  {34,GrammarCharset26CharCount,GrammarCharset26},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray34[2+1] = {
  {14,GrammarCharset36CharCount,GrammarCharset36},
  {35,GrammarCharset37CharCount,GrammarCharset37},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray35[2+1] = {
  {14,GrammarCharset31CharCount,GrammarCharset31},
  {36,GrammarCharset32CharCount,GrammarCharset32},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray36[1+1] = {
  {14,GrammarCharset17CharCount,GrammarCharset17},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray37[2+1] = {
  {14,GrammarCharset35CharCount,GrammarCharset35},
  {38,GrammarCharset16CharCount,GrammarCharset16},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray38[2+1] = {
  {14,GrammarCharset33CharCount,GrammarCharset33},
  {39,GrammarCharset34CharCount,GrammarCharset34},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray39[1+1] = {
  {14,GrammarCharset17CharCount,GrammarCharset17},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray40[2+1] = {
  {14,GrammarCharset38CharCount,GrammarCharset38},
  {41,GrammarCharset39CharCount,GrammarCharset39},
  {-1,0,NULL}};
struct DfaEdgeStruct GrammarDfaEdgeArray41[1+1] = {
  {14,GrammarCharset17CharCount,GrammarCharset17},
  {-1,0,NULL}};



int GrammarRuleSymbolArray0[2+1] = {
  19,
  23,
  -1};
int GrammarRuleSymbolArray1[2+1] = {
  8,
  22,
  -1};
int GrammarRuleSymbolArray2[2+1] = {
  18,
  22,
  -1};
int GrammarRuleSymbolArray3[0+1] = {
  -1};
int GrammarRuleSymbolArray4[1+1] = {
  11,
  -1};
int GrammarRuleSymbolArray5[2+1] = {
  14,
  19,
  -1};
int GrammarRuleSymbolArray6[2+1] = {
  21,
  19,
  -1};
int GrammarRuleSymbolArray7[2+1] = {
  11,
  17,
  -1};
int GrammarRuleSymbolArray8[2+1] = {
  16,
  17,
  -1};
int GrammarRuleSymbolArray9[3+1] = {
  6,
  22,
  7,
  -1};
int GrammarRuleSymbolArray10[3+1] = {
  6,
  25,
  7,
  -1};
int GrammarRuleSymbolArray11[1+1] = {
  24,
  -1};
int GrammarRuleSymbolArray12[3+1] = {
  25,
  8,
  24,
  -1};
int GrammarRuleSymbolArray13[1+1] = {
  16,
  -1};
int GrammarRuleSymbolArray14[1+1] = {
  11,
  -1};
int GrammarRuleSymbolArray15[1+1] = {
  20,
  -1};
int GrammarRuleSymbolArray16[2+1] = {
  16,
  17,
  -1};
int GrammarRuleSymbolArray17[1+1] = {
  10,
  -1};
int GrammarRuleSymbolArray18[1+1] = {
  15,
  -1};
int GrammarRuleSymbolArray19[1+1] = {
  13,
  -1};
int GrammarRuleSymbolArray20[2+1] = {
  9,
  16,
  -1};
int GrammarRuleSymbolArray21[2+1] = {
  12,
  16,
  -1};
int GrammarRuleSymbolArray22[3+1] = {
  6,
  21,
  7,
  -1};


struct ActionStruct GrammarLalrActionArray0[9+1] = {
  {6,1,1},
  {9,1,2},
  {11,1,3},
  {12,1,4},
  {14,1,5},
  {16,1,6},
  {19,3,7},
  {21,3,8},
  {22,3,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray1[9+1] = {
  {6,1,1},
  {9,1,2},
  {11,1,3},
  {12,1,4},
  {14,1,5},
  {16,1,6},
  {19,3,7},
  {21,3,10},
  {22,3,11},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray2[1+1] = {
  {16,1,12},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray3[8+1] = {
  {6,1,13},
  {17,3,14},
  {0,2,4},
  {7,2,4},
  {8,2,4},
  {10,2,4},
  {13,2,4},
  {15,2,4},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray4[1+1] = {
  {16,1,15},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray5[8+1] = {
  {6,1,1},
  {9,1,2},
  {11,1,3},
  {12,1,4},
  {14,1,5},
  {16,1,6},
  {19,3,16},
  {21,3,8},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray6[2+1] = {
  {6,1,13},
  {17,3,17},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray7[8+1] = {
  {8,1,18},
  {10,1,19},
  {13,1,20},
  {15,1,21},
  {18,3,22},
  {23,3,23},
  {0,2,3},
  {7,2,3},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray8[8+1] = {
  {6,1,1},
  {9,1,2},
  {11,1,3},
  {12,1,4},
  {14,1,5},
  {16,1,6},
  {19,3,24},
  {21,3,8},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray9[1+1] = {
  {0,4,0},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray10[9+1] = {
  {6,1,1},
  {7,1,25},
  {9,1,2},
  {11,1,3},
  {12,1,4},
  {14,1,5},
  {16,1,6},
  {19,3,24},
  {21,3,8},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray11[1+1] = {
  {7,1,26},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray12[7+1] = {
  {6,2,20},
  {7,2,20},
  {9,2,20},
  {11,2,20},
  {12,2,20},
  {14,2,20},
  {16,2,20},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray13[5+1] = {
  {11,1,27},
  {16,1,28},
  {20,3,29},
  {24,3,30},
  {25,3,31},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray14[6+1] = {
  {0,2,7},
  {7,2,7},
  {8,2,7},
  {10,2,7},
  {13,2,7},
  {15,2,7},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray15[7+1] = {
  {6,2,21},
  {7,2,21},
  {9,2,21},
  {11,2,21},
  {12,2,21},
  {14,2,21},
  {16,2,21},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray16[6+1] = {
  {0,2,5},
  {7,2,5},
  {8,2,5},
  {10,2,5},
  {13,2,5},
  {15,2,5},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray17[6+1] = {
  {0,2,8},
  {7,2,8},
  {8,2,8},
  {10,2,8},
  {13,2,8},
  {15,2,8},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray18[9+1] = {
  {6,1,1},
  {9,1,2},
  {11,1,3},
  {12,1,4},
  {14,1,5},
  {16,1,6},
  {19,3,7},
  {21,3,8},
  {22,3,32},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray19[6+1] = {
  {6,2,17},
  {9,2,17},
  {11,2,17},
  {12,2,17},
  {14,2,17},
  {16,2,17},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray20[6+1] = {
  {6,2,19},
  {9,2,19},
  {11,2,19},
  {12,2,19},
  {14,2,19},
  {16,2,19},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray21[6+1] = {
  {6,2,18},
  {9,2,18},
  {11,2,18},
  {12,2,18},
  {14,2,18},
  {16,2,18},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray22[9+1] = {
  {6,1,1},
  {9,1,2},
  {11,1,3},
  {12,1,4},
  {14,1,5},
  {16,1,6},
  {19,3,7},
  {21,3,8},
  {22,3,33},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray23[2+1] = {
  {0,2,0},
  {7,2,0},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray24[6+1] = {
  {0,2,6},
  {7,2,6},
  {8,2,6},
  {10,2,6},
  {13,2,6},
  {15,2,6},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray25[7+1] = {
  {6,2,22},
  {7,2,22},
  {9,2,22},
  {11,2,22},
  {12,2,22},
  {14,2,22},
  {16,2,22},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray26[6+1] = {
  {0,2,9},
  {7,2,9},
  {8,2,9},
  {10,2,9},
  {13,2,9},
  {15,2,9},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray27[2+1] = {
  {7,2,14},
  {8,2,14},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray28[4+1] = {
  {6,1,13},
  {17,3,34},
  {7,2,13},
  {8,2,13},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray29[2+1] = {
  {7,2,15},
  {8,2,15},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray30[2+1] = {
  {7,2,11},
  {8,2,11},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray31[2+1] = {
  {7,1,35},
  {8,1,36},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray32[2+1] = {
  {0,2,1},
  {7,2,1},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray33[2+1] = {
  {0,2,2},
  {7,2,2},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray34[2+1] = {
  {7,2,16},
  {8,2,16},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray35[6+1] = {
  {0,2,10},
  {7,2,10},
  {8,2,10},
  {10,2,10},
  {13,2,10},
  {15,2,10},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray36[4+1] = {
  {11,1,27},
  {16,1,28},
  {20,3,29},
  {24,3,37},
  {-1,-1,-1}};
struct ActionStruct GrammarLalrActionArray37[2+1] = {
  {7,2,12},
  {8,2,12},
  {-1,-1,-1}};



/*
struct SymbolStruct {
  short Kind;
  wchar_t *Name;
  };
*/
struct SymbolStruct GrammarSymbolArray[26] = {
  /*  0 */   {3,L"EOF"},
  /*  1 */   {7,L"Error"},
  /*  2 */   {2,L"Whitespace"},
  /*  3 */   {5,L"Comment End"},
  /*  4 */   {6,L"Comment Line"},
  /*  5 */   {4,L"Comment Start"},
  /*  6 */   {1,L"("},
  /*  7 */   {1,L")"},
  /*  8 */   {1,L","},
  /*  9 */   {1,L"all"},
  /* 10 */   {1,L"and"},
  /* 11 */   {1,L"con"},
  /* 12 */   {1,L"exists"},
  /* 13 */   {1,L"modus"},
  /* 14 */   {1,L"not"},
  /* 15 */   {1,L"or"},
  /* 16 */   {1,L"var"},
  /* 17 */   {0,L"argument-list"},
  /* 18 */   {0,L"binary-operator"},
  /* 19 */   {0,L"formula"},
  /* 20 */   {0,L"function"},
  /* 21 */   {0,L"quantifier"},
  /* 22 */   {0,L"source"},
  /* 23 */   {0,L"tail"},
  /* 24 */   {0,L"term"},
  /* 25 */   {0,L"term-list"} 
  };



/*
struct DfaEdgeStruct {
  int TargetState;
  wchar_t *CharacterSet;
  };
struct DfaStateStruct {
  int AcceptSymbol;
  int EdgeCount;
  struct DfaEdgeStruct *Edges;
  };
*/
struct DfaStateStruct GrammarDfaStateArray[42+1] = {
  /* 0 */    {-1,17,GrammarDfaEdgeArray0},
  /* 1 */    {2,1,GrammarDfaEdgeArray1},
  /* 2 */    {-1,1,GrammarDfaEdgeArray2},
  /* 3 */    {3,0,GrammarDfaEdgeArray3},
  /* 4 */    {4,0,GrammarDfaEdgeArray4},
  /* 5 */    {-1,1,GrammarDfaEdgeArray5},
  /* 6 */    {4,0,GrammarDfaEdgeArray6},
  /* 7 */    {4,0,GrammarDfaEdgeArray7},
  /* 8 */    {6,0,GrammarDfaEdgeArray8},
  /* 9 */    {7,0,GrammarDfaEdgeArray9},
  /* 10 */    {8,0,GrammarDfaEdgeArray10},
  /* 11 */    {11,1,GrammarDfaEdgeArray11},
  /* 12 */    {11,1,GrammarDfaEdgeArray12},
  /* 13 */    {16,1,GrammarDfaEdgeArray13},
  /* 14 */    {16,1,GrammarDfaEdgeArray14},
  /* 15 */    {-1,2,GrammarDfaEdgeArray15},
  /* 16 */    {4,0,GrammarDfaEdgeArray16},
  /* 17 */    {5,0,GrammarDfaEdgeArray17},
  /* 18 */    {11,2,GrammarDfaEdgeArray18},
  /* 19 */    {11,2,GrammarDfaEdgeArray19},
  /* 20 */    {4,1,GrammarDfaEdgeArray20},
  /* 21 */    {16,3,GrammarDfaEdgeArray21},
  /* 22 */    {16,2,GrammarDfaEdgeArray22},
  /* 23 */    {9,1,GrammarDfaEdgeArray23},
  /* 24 */    {16,2,GrammarDfaEdgeArray24},
  /* 25 */    {10,1,GrammarDfaEdgeArray25},
  /* 26 */    {16,2,GrammarDfaEdgeArray26},
  /* 27 */    {16,2,GrammarDfaEdgeArray27},
  /* 28 */    {16,2,GrammarDfaEdgeArray28},
  /* 29 */    {16,2,GrammarDfaEdgeArray29},
  /* 30 */    {16,2,GrammarDfaEdgeArray30},
  /* 31 */    {12,1,GrammarDfaEdgeArray31},
  /* 32 */    {16,2,GrammarDfaEdgeArray32},
  /* 33 */    {16,2,GrammarDfaEdgeArray33},
  /* 34 */    {16,2,GrammarDfaEdgeArray34},
  /* 35 */    {16,2,GrammarDfaEdgeArray35},
  /* 36 */    {13,1,GrammarDfaEdgeArray36},
  /* 37 */    {16,2,GrammarDfaEdgeArray37},
  /* 38 */    {16,2,GrammarDfaEdgeArray38},
  /* 39 */    {14,1,GrammarDfaEdgeArray39},
  /* 40 */    {16,2,GrammarDfaEdgeArray40},
  /* 41 */    {15,1,GrammarDfaEdgeArray41},
  {-1,-1,NULL}};



/*
struct RuleStruct {
  int Head;
  int SymbolsCount;
  int *Symbols;
  wchar_t *Description;
  };
*/
struct RuleStruct GrammarRuleArray[23] = {
  /*  0 */   {22,2,GrammarRuleSymbolArray0,L"<source> ::= <formula> <tail>"},
  /*  1 */   {23,2,GrammarRuleSymbolArray1,L"<tail> ::= ',' <source>"},
  /*  2 */   {23,2,GrammarRuleSymbolArray2,L"<tail> ::= <binary-operator> <source>"},
  /*  3 */   {23,0,GrammarRuleSymbolArray3,L"<tail> ::= "},
  /*  4 */   {19,1,GrammarRuleSymbolArray4,L"<formula> ::= con"},
  /*  5 */   {19,2,GrammarRuleSymbolArray5,L"<formula> ::= not <formula>"},
  /*  6 */   {19,2,GrammarRuleSymbolArray6,L"<formula> ::= <quantifier> <formula>"},
  /*  7 */   {19,2,GrammarRuleSymbolArray7,L"<formula> ::= con <argument-list>"},
  /*  8 */   {19,2,GrammarRuleSymbolArray8,L"<formula> ::= var <argument-list>"},
  /*  9 */   {19,3,GrammarRuleSymbolArray9,L"<formula> ::= '(' <source> ')'"},
  /* 10 */   {17,3,GrammarRuleSymbolArray10,L"<argument-list> ::= '(' <term-list> ')'"},
  /* 11 */   {25,1,GrammarRuleSymbolArray11,L"<term-list> ::= <term>"},
  /* 12 */   {25,3,GrammarRuleSymbolArray12,L"<term-list> ::= <term-list> ',' <term>"},
  /* 13 */   {24,1,GrammarRuleSymbolArray13,L"<term> ::= var"},
  /* 14 */   {24,1,GrammarRuleSymbolArray14,L"<term> ::= con"},
  /* 15 */   {24,1,GrammarRuleSymbolArray15,L"<term> ::= <function>"},
  /* 16 */   {20,2,GrammarRuleSymbolArray16,L"<function> ::= var <argument-list>"},
  /* 17 */   {18,1,GrammarRuleSymbolArray17,L"<binary-operator> ::= and"},
  /* 18 */   {18,1,GrammarRuleSymbolArray18,L"<binary-operator> ::= or"},
  /* 19 */   {18,1,GrammarRuleSymbolArray19,L"<binary-operator> ::= modus"},
  /* 20 */   {21,2,GrammarRuleSymbolArray20,L"<quantifier> ::= all var"},
  /* 21 */   {21,2,GrammarRuleSymbolArray21,L"<quantifier> ::= exists var"},
  /* 22 */   {21,3,GrammarRuleSymbolArray22,L"<quantifier> ::= '(' <quantifier> ')'"} 
  };



/*
struct ActionStruct {
  int Entry;
  short Action;
  int Target;
  };
struct LalrStateStruct {
  int ActionCount;
  struct ActionStruct *Actions;
  };
*/
struct LalrStateStruct GrammarLalrStateArray[38+1] = {
  /* 0 */   {9,GrammarLalrActionArray0},
  /* 1 */   {9,GrammarLalrActionArray1},
  /* 2 */   {1,GrammarLalrActionArray2},
  /* 3 */   {8,GrammarLalrActionArray3},
  /* 4 */   {1,GrammarLalrActionArray4},
  /* 5 */   {8,GrammarLalrActionArray5},
  /* 6 */   {2,GrammarLalrActionArray6},
  /* 7 */   {8,GrammarLalrActionArray7},
  /* 8 */   {8,GrammarLalrActionArray8},
  /* 9 */   {1,GrammarLalrActionArray9},
  /* 10 */   {9,GrammarLalrActionArray10},
  /* 11 */   {1,GrammarLalrActionArray11},
  /* 12 */   {7,GrammarLalrActionArray12},
  /* 13 */   {5,GrammarLalrActionArray13},
  /* 14 */   {6,GrammarLalrActionArray14},
  /* 15 */   {7,GrammarLalrActionArray15},
  /* 16 */   {6,GrammarLalrActionArray16},
  /* 17 */   {6,GrammarLalrActionArray17},
  /* 18 */   {9,GrammarLalrActionArray18},
  /* 19 */   {6,GrammarLalrActionArray19},
  /* 20 */   {6,GrammarLalrActionArray20},
  /* 21 */   {6,GrammarLalrActionArray21},
  /* 22 */   {9,GrammarLalrActionArray22},
  /* 23 */   {2,GrammarLalrActionArray23},
  /* 24 */   {6,GrammarLalrActionArray24},
  /* 25 */   {7,GrammarLalrActionArray25},
  /* 26 */   {6,GrammarLalrActionArray26},
  /* 27 */   {2,GrammarLalrActionArray27},
  /* 28 */   {4,GrammarLalrActionArray28},
  /* 29 */   {2,GrammarLalrActionArray29},
  /* 30 */   {2,GrammarLalrActionArray30},
  /* 31 */   {2,GrammarLalrActionArray31},
  /* 32 */   {2,GrammarLalrActionArray32},
  /* 33 */   {2,GrammarLalrActionArray33},
  /* 34 */   {2,GrammarLalrActionArray34},
  /* 35 */   {6,GrammarLalrActionArray35},
  /* 36 */   {4,GrammarLalrActionArray36},
  /* 37 */   {2,GrammarLalrActionArray37},
  {-1,NULL}};



/*
struct GrammarStruct {
  char CaseSensitive;
  int InitialSymbol;
  int InitialDfaState;
  int InitialLalrState;
  int SymbolCount;
  struct SymbolStruct *SymbolArray;
  int RuleCount;
  struct RuleStruct *RuleArray;
  int DfaStateCount;
  struct DfaStateStruct *DfaArray;
  int LalrStateCount;
  struct LalrStateStruct *LalrArray;
  };
*/
struct GrammarStruct Grammar = {
  /* CaseSensitive */      True,
  /* InitialSymbol */      22,
  /* InitialDfaState */    0,
  /* InitialLalrState */   0,
  /* SymbolCount */        26,
  /* SymbolArray */        GrammarSymbolArray,
  /* RuleCount */          23,
  /* RuleArray */          GrammarRuleArray,
  /* DfaStateCount */      42,
  /* DfaArray */           GrammarDfaStateArray,
  /* LalrStateCount */     38,
  /* LalrArray */          GrammarLalrStateArray
  };
